CAVASOL/Kinder-projects

- Gemfile
- app/models/user.rb
- db/migrate/20211207051112_add_about_me_to_users.rb
- db/migrate/20211207051159_add_level_to_users.rb
- db/migrate/20211207052224_add_time_fields_to_projects.rb
- db/migrate/20211207052732_create_active_storage_tables.active_storage.rb
- db/schema.rb
- db/seeds.rb
> seeds fixed

- app/controllers/projects_controller.rb
- app/controllers/volunteerings_controller.rb
- app/models/project.rb
- config/routes.rb
volunteering controller pages controller and both views and routes done
> volunteering controller pages controller and both views and routes done

- app/controllers/volunteerings_controller.rb
- app/models/volunteering.rb
Created action CREATE for volunteerings controller
Updated the model Volunteering with the constants variable:
VOLUNTEER_STATUS = %w[pending confirmed rejected]
> create action for volunteerings controller

- app/controllers/pages_controller.rb
fixed pages controller indentation
> fixed eye indentation

- app/views/pages/dashboard.html.erb
Dashboard fixed: added volunteering list and projects list into the dashboard
> Dashboard editing

- app/controllers/pages_controller.rb
- app/controllers/projects_controller.rb
- app/controllers/volunteerings_controller.rb
- app/views/projects/show.html.erb
> Improve volunteering feature

- app/views/projects/show.html.erb
Changed button name for volunteering
> Changed button name for volunteering

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_index.scss
- app/views/pages/dashboard.html.erb
- config/environments/development.rb
- config/environments/production.rb
- config/storage.yml
Fixed dashboard - dashboard ables to list my projects and my volunteering projects
> Dashboard card

- config/environments/development.rb
- config/storage.yml
fixed dashboard classes and container to become more readable and concise
> Beautify projects

- app/assets/stylesheets/components/_card.scss
- app/views/pages/dashboard.html.erb
- app/views/projects/show.html.erb
Changed dashboard code and fixed link to edit and more info
> Dashboard changed

- app/assets/stylesheets/pages/_profile.scss
- app/controllers/application_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/users_controller.rb
- app/views/devise/registrations/edit.html.erb
- app/views/pages/dashboard.html.erb
- app/views/pages/profile.html.erb
Fixes on dashboard and profile avatar.
> User profile view

- app/assets/stylesheets/pages/_profile.scss
- app/controllers/pages_controller.rb
- app/views/pages/profile.html.erb
Fixed profile queries and log out link
> fixed profile queries and log out link

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_project_list.scss
- app/assets/stylesheets/pages/_banner.scss
- app/views/pages/home.html.erb
- app/views/projects/index.html.erb
Project index page 1st version.
> Project index

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/components/_project_list.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/projects/index.html.erb
- app/views/shared/_navbar.html.erb
- Explore btn on nav fixed / relocated to landing
- index page margin added
- footer added
> page margin and footer added

- app/views/shared/_navbar.html.erb
nav title fixed explore to home on project index page
> nav title fixed

- app/assets/stylesheets/components/_project_list.scss
- app/views/projects/index.html.erb
Project location and status added with icons
> Project index card design changed

- app/assets/stylesheets/components/_project_list.scss
- app/views/devise/registrations/new.html.erb
- app/views/projects/index.html.erb
- app/views/shared/_navbar.html.erb
- Project date added 
- Card design changed as clickable
> Project card clickable

- app/views/pages/dashboard.html.erb
fixed dashboard bootstrap link
> fixed dashboard bootstrap link

- app/views/layouts/application.html.erb
- app/views/shared/_navbar.html.erb
- Project btn with home
- Profile btn
> Bottom nav btn bug fixed

- app/views/pages/dashboard.html.erb
- app/views/projects/show.html.erb
remove my volunteers from dashboard and added it to pages show
> remove my volunteers from dashboard and added it to pages show

- app/controllers/projects_controller.rb
- app/views/pages/dashboard.html.erb
- app/views/projects/show.html.erb
Project details and volunteers
> Project details

- app/views/projects/show.html.erb
resolved conflict and rule for edit/cancel button
> Project page cancel button

- app/controllers/volunteerings_controller.rb
- app/models/volunteering.rb
- app/views/projects/show.html.erb
- config/routes.rb
fixed controller and validation test
> controller fixed

- app/controllers/inboxs_controller.rb
- app/controllers/messages_controller.rb
- app/controllers/pages_controller.rb
- app/views/messages/index.html.erb
- app/views/pages/inbox.html.erb
- config/routes.rb
- db/schema.rb
- test/controllers/inboxs_controller_test.rb
- test/controllers/messages_controller_test.rb
finished the basic messaging controller routes and view
> Inbox feature work

- db/schema.rb
- db/seeds.rb
"fixing the seed 65 character problems"
> fixing the seed 65 character problems

- app/controllers/projects_controller.rb
Gamification volunteer confirmation rules on project controller
> Gamification volunteer confirmation

- app/controllers/messages_controller.rb
- app/views/messages/index.html.erb
Messaging feature is done now it needs styling
> Messaging feature

- app/views/pages/dashboard.html.erb
Fixed the margin bottom between cards on the dashboard.
> Fix spacing

- app/assets/stylesheets/pages/_profile.scss
- app/views/pages/dashboard.html.erb
- app/views/pages/profile.html.erb
- app/views/shared/_user_level.html.erb
Standardise profile and my projects page (avatar and bar)
Fix styling on profile page (change the edit button to be bigger)
> Dashboard styling

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/config/_fonts.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
- app/views/shared/_footer.html.erb
Add Social media icons and changed font to be Roboto
> Footer-font-style

- app/assets/stylesheets/pages/_chatroom.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/messages/_last_message.html.erb
- app/views/messages/index.html.erb
chatroom styling fixed and navigation back to inbox path
> Html scss message room

- app/views/messages/index.html.erb
fixed navigation on chatroom to go back to inbox path
> Chatroom message icon

- app/assets/stylesheets/pages/_chatroom.scss
- app/views/messages/_message.html.erb
- app/views/messages/index.html.erb
chatroom finished styling and coloring for current user and other user
> chatroom finished styling and coloring for current user and other user

- app/assets/stylesheets/pages/_chatroom.scss
fixed top border on the chatroom
> fixed top border on the chatroom

- config/cable.yml
added websocket redis for heroku for chatroom
> added websocket redis for heroku

- app/assets/stylesheets/pages/_profile.scss
- app/views/pages/profile.html.erb
> log-out-profile

- app/controllers/application_controller.rb
- app/controllers/inboxs_controller.rb
- app/controllers/projects_controller.rb
- app/models/project.rb
- app/views/projects/about.html.erb
automatic expiration of projects
> Automatic closed status

- app/views/projects/index.html.erb
Sponsor can't save their own project to wishlist.
> Wishlist icon fixed

- app/assets/stylesheets/pages/_inbox.scss
- app/views/pages/dashboard.html.erb
- app/views/pages/inbox.html.erb
Fixed empty lists display in dashboard and inbox.
> Empty lists fix

- app/views/pages/dashboard.html.erb
Conflict characters appeared on history view, deleted
> conflict characters appeared on history view, deleted

- app/assets/stylesheets/pages/_chatroom.scss
- app/controllers/messages_controller.rb
- app/models/message.rb
- app/views/messages/_message.html.erb
- app/views/messages/index.html.erb
'chatroom attachment done and styling needed javascript afterlunch'
> Finishing touch work

- app/assets/stylesheets/pages/_inbox.scss
- app/views/pages/inbox.html.erb
Margin bottom and div fix on Inbox view.
> Inbox footer space

- app/assets/stylesheets/pages/_chatroom.scss
- app/views/layouts/application.html.erb
- app/views/messages/index.html.erb
search bar on chatroom fixed and removed the navbar
> Search form chatroom fixed

- app/assets/stylesheets/pages/_profile.scss
- app/views/users/show.html.erb
> Volunteer profile edit

- app/assets/stylesheets/pages/_chatroom.scss
> fixed position search bar

- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_simple_form.scss
> Simple form

- app/assets/stylesheets/components/_buttom.scss
- app/views/pages/inbox.html.erb
- app/views/projects/about.html.erb
Styling change on project about page and inbox
> Project page styling

- app/assets/stylesheets/pages/_chatroom.scss
chatroom message content fixed
> chatroom message content fixed

- app/views/layouts/application.html.erb
> Head title changed

- app/controllers/application_controller.rb
- app/views/pages/profile.html.erb
- app/views/projects/show.html.erb
Separate cards on profile, fix redirect after create and update to dashboard, corrected margin and aligned style of volunteers in project card.
> Profile alignment and redirect after update and create

- app/assets/stylesheets/pages/_profile.scss
- app/views/pages/profile.html.erb
Added explanation to kinder levels.
> Levels legend

- app/controllers/pages_controller.rb
unconfirm volunteer wouldnt have access to the chatroom
> unconfirm volunteer wouldnt have access to the chatroom

- app/views/shared/_top_navbar.html.erb
Changed the redirect to back in top navbar.
> navbar-back
